### ISSUE TITLE
Release 2.1.0

### ISSUE THREAD

**Issue by naomijub** [jfacorro/Eden#39]
Can you make a release of version `2.1.0`? As well as publish it to HEX?
Maybe convert your fork `jfacorro/elixir-array` into a new HEX lib? like `eden-array`.

Also, congrats! this is the only other non-Clojure EDN lib that I have seen that matches EDN Spec nicely!

**Comment by jfacorro** [comment]
Hi @naomijub! I'm happy you have found this library useful 😄 .

I can bump the library and make a release. I now realise I never published `2.0.0` 🤦 .

Are you suggesting renaming `jfacorro/elixir-array` and publishing it to hex to avoid depending on github?

**Comment by naomijub** [comment]
Thanks

> Are you suggesting renaming jfacorro/elixir-array and publishing it to hex to avoid depending on github?

Yes

**Comment by jfacorro** [comment]
There's currently no pipeline being run for the project and elixir 1.11 is not yet available in [official docker repostory](https://hub.docker.com/_/elixir).

Before releasing anything I would like to check that this changes work. Compiling and running the tests locally show a bunch of warnings which I would like to get rid of before publishing.

**Comment by naomijub** [comment]
Sure give me a `@`  when this is ready

**Comment by naomijub** [comment]
if it helps, I am using it here https://github.com/naomijub/translixir

**Comment by jfacorro** [comment]
Further work is needed, trying to publish the current HEAD fails:
```
➜  Eden git:(master) mix hex.publish
warning: variable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
  /Users/juan.facorro/dev/jfacorro/Eden/deps/array/mix.exs:9: Array.Mixfile.project/0

warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  /Users/juan.facorro/dev/jfacorro/Eden/deps/array/mix.exs:10: Array.Mixfile.project/0

warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  /Users/juan.facorro/dev/jfacorro/Eden/deps/exreloader/mix.exs:7: Exreloader.Mixfile.project/0

Building eden 2.1.0
  Dependencies:
    timex ~> 3.1 (app: timex)
  App: eden
  Name: eden
  Files:
    lib
    lib/eden.ex
    lib/eden
    lib/eden/types.ex
    lib/eden/exception.ex
    lib/eden/encode.ex
    lib/eden/parser
    lib/eden/parser/node.ex
    lib/eden/decode.ex
    lib/eden/parser.ex
    lib/eden/lexer.ex
    mix.exs
    README.md
    LICENSE
  Version: 2.1.0
  Build tools: mix
  Description: edn (extensible data notation) encoder/decoder implemented in Elixir.
  Licenses: Apache 2.0
  Links:
    GitHub: https://github.com/jfacorro/Eden/
    edn format: https://github.com/edn-format/edn
  Elixir: ~> 1.11
** (Mix) Stopping package build due to errors.
Dependencies excluded from the package (only Hex packages can be dependencies): array
```

**Comment by jfacorro** [comment]
> if it helps, I am using it here https://github.com/naomijub/translixir

It does help, thank you! 😄

**Comment by jfacorro** [comment]
[2.1.0 Released!](https://hex.pm/packages/eden) 🥳
